In [52]:
#import numpy libray

import numpy as np
import random 

In [53]:
#creat simple array from the list

arr = np.array([[4,5,6,5],[5,6,7,8]])
arr

array([[4, 5, 6, 5],
       [5, 6, 7, 8]])

In [54]:
arr.ndim # dimension

2

In [55]:
arr.shape #shape of array

(2, 4)

In [56]:
type (arr)

numpy.ndarray

In [57]:
arr.data #memory Location

# Random number generator using numpy

In [59]:
x= np.random.randint(2000)
x

1875

In [61]:
#generate random float

x= np.random.rand()
x

0.961692380120991

In [62]:
x= np.random.rand(5)
x

array([0.22216179, 0.69284681, 0.38977165, 0.33808201, 0.27668152])

In [63]:
x= np.random.randint(100, size=(5))
x

array([54, 39, 58, 77, 37])

In [64]:
x= np.random.randint(100, size=(5))
print(x)

[18 65 29 95 83]


In [67]:
x= np.random.randint(100, size=(3,5))
x

array([[36, 94, 87, 93, 63],
       [37, 54, 65, 42, 74],
       [46, 15, 37, 13,  3]])

In [68]:
x.ndim

2

# x=10 random integer array 0 to 1000


# y= 10 random integer array 0 to 500


# math operation

In [69]:
x= np.random.randint(1000, size=(10))
x

array([930, 973, 835, 837, 768, 696, 617, 685, 503,   6])

In [71]:
y= np.random.randint(500, size=(10))
y

array([142,  13, 196, 407, 360, 151, 307, 100,  12, 128])

In [72]:
z =x+y
z

array([1072,  986, 1031, 1244, 1128,  847,  924,  785,  515,  134])

In [73]:
z =x-y
z

array([ 788,  960,  639,  430,  408,  545,  310,  585,  491, -122])

In [74]:
z= x*y
z

array([132060,  12649, 163660, 340659, 276480, 105096, 189419,  68500,
         6036,    768])

In [76]:
z= x/y
z

array([4.61218012e-02, 5.75739645e+00, 2.17357351e-02, 5.05285272e-03,
       5.92592593e-03, 3.05249770e-02, 6.54648856e-03, 6.85000000e-02,
       3.49305556e+00, 3.66210938e-04])

In [77]:
z= x**y
z

array([7.93658720e+115, 2.31314759e+024, 2.33538889e+123, 2.78187011e+127,
       2.89160479e+118, 1.61612943e+100, 1.16429783e+093, 3.70729503e+083,
       2.94198780e+019, 7.59423329e-171])

In [78]:
a= np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [79]:
#array like input
b= np.matrix([[5,4,3],[4,5,7]])
b

matrix([[5, 4, 3],
        [4, 5, 7]])

# measurement of central tendency using numpy

In [85]:
arr= np.array([[1,56,67], [5,54,66], [2,3,4]])
print(arr)
arr.shape

[[ 1 56 67]
 [ 5 54 66]
 [ 2  3  4]]


(3, 3)

In [86]:
np.amin(arr) #minimum value

1

In [87]:
np.amax(arr) #maximun value

67

In [88]:
np.mean(arr) #mean

28.666666666666668

In [89]:
np.var(arr) #variance

839.5555555555554

In [91]:
np.std(arr) #standard deviation

28.975085082800973

In [92]:
np.median(arr) #median

5.0